### ISSUE TITLE
TODO Items to finalize AZD template

### ISSUE THREAD

**Issue by seesharprun** [Azure-Samples/cosmos-db-nosql-java-quickstart#3]
- [x] Add Dockerfile for Spring web application
- [x] Get `mvn spring-boot:run` working within the GitHub Codespaces development container
- [x] Add validation steps to build and test the application to the workflow
- [x] Update readme
